# Generated by Django 6.0.8 on 2026-08-24 13:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_lesson_video_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_start', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('provider', models.CharField(choices=[('external', 'External link (Meet/Zoom)'), ('livekit', 'Native (LiveKit)')], default='external', max_length=20)),
                ('join_url', models.URLField(blank=True)),
                ('room_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('recording_key', models.CharField(blank=True, max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='courses.course')),
            ],
            options={
                'ordering': ('scheduled_start',),
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='liveclasses.liveclass')),
            ],
        ),
        migrations.AddIndex(
            model_name='liveclass',
            index=models.Index(fields=['course', 'scheduled_start'], name='liveclasses_course__a01095_idx'),
        ),
        migrations.AddIndex(
            model_name='liveclass',
            index=models.Index(fields=['status', 'scheduled_start'], name='liveclasses_status_43eaf8_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['live_class', 'student'], name='liveclasses_live_cl_33669d_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('live_class', 'student'), name='uq_attendance'),
        ),
    ]
