# Generated by Django 6.0.8 on 2026-08-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
