# Generated by Django 6.0.8 on 2026-09-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='short_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('review', 'Under Review'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('late', 'Late')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
