name = "vaceup-frontend"
compatibility_date = "2026-08-31"

[build]
command = "npm run build"
cwd = "frontend"

pages_build_output_dir = ".next"

[env]
NEXT_PUBLIC_API_URL = "https://api.vaceup.ng"

[vars]
BACKEND_URL = "https://api.vaceup.ng"