# Generated by Django 5.2.17 on 2026-09-19 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(max_length=1000)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='message',
            name='client_message_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(max_length=5000),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'recipient', 'id'], name='msg_thread_id_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='msg_sender_time_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'sender', 'is_read', 'id'], name='msg_unread_thread_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('sender', 'client_message_id'), name='uq_message_sender_client_id'),
        ),
        migrations.AddField(
            model_name='messageblock',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_blocks_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageblock',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_blocks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='messageblock',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='uq_message_block'),
        ),
        migrations.AddConstraint(
            model_name='messageblock',
            constraint=models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='message_block_not_self'),
        ),
        migrations.AddConstraint(
            model_name='messagereport',
            constraint=models.UniqueConstraint(fields=('message', 'reporter'), name='uq_message_report'),
        ),
    ]
