# Generated by Django 6.0.8 on 2026-09-01 20:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_lesson_video_key'),
        ('enrollment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('html_template', models.TextField(help_text='HTML template with Jinja2 placeholders')),
                ('css_styles', models.TextField(blank=True, default='')),
                ('page_size', models.CharField(choices=[('A4', 'A4'), ('Letter', 'Letter')], default='A4', max_length=10)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, help_text='Null = global template for all courses without specific template', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='courses.course')),
            ],
            options={
                'ordering': ('-is_default', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('verification_code', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('student_name_at_issue', models.CharField(max_length=200)),
                ('course_title_at_issue', models.CharField(max_length=200)),
                ('instructor_name_at_issue', models.CharField(max_length=200)),
                ('institution_name_at_issue', models.CharField(default='VaceUp', max_length=200)),
                ('completion_date', models.DateField()),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to='courses.course')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='enrollment.enrollment')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_certificates', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_certificates', to='certificates.certificatetemplate')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CertificateVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='certificates.certificate')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='certificatetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('course', 'is_default'), name='unique_default_template_per_course'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['student', 'course'], name='certificate_student_9f3e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_number'], name='certificate_certifi_cd0c46_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['verification_code'], name='certificate_verific_e033f7_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['status'], name='certificate_status_31e804_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_certificate_per_student_course'),
        ),
        migrations.AddIndex(
            model_name='certificateverificationlog',
            index=models.Index(fields=['certificate', '-created_at'], name='certificate_certifi_0eceef_idx'),
        ),
    ]
