# Generated by Django 6.0.8 on 2026-09-01 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEditorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_id', models.UUIDField(db_index=True, unique=True)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('java', 'Java'), ('cpp', 'C++'), ('go', 'Go'), ('rust', 'Rust'), ('csharp', 'C#')], default='python', max_length=20)),
                ('crdt_state', models.BinaryField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['room_id', 'is_active'], name='codeeditor__room_id_9d5778_idx')],
            },
        ),
        migrations.CreateModel(
            name='CodeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('stdin', models.TextField(blank=True)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(null=True)),
                ('duration_ms', models.PositiveIntegerField(null=True)),
                ('memory_mb', models.FloatField(null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='codeeditor.codeeditorsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['session', '-created_at'], name='codeeditor__session_c0edd7_idx'), models.Index(fields=['user', '-created_at'], name='codeeditor__user_id_18e12c_idx')],
            },
        ),
    ]
