# Generated by Django 5.2.17 on 2026-09-13 10:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_admin_guide_dismissed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=24)),
                ('object_id', models.PositiveBigIntegerField()),
                ('dedupe_key', models.CharField(max_length=180, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Accepted by SMTP'), ('skipped', 'No longer applicable'), ('failed', 'Needs attention')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_id', models.UUIDField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=48)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'available_at'], name='mail_job_due_idx')],
            },
        ),
    ]
