# Generated by Django 6.0.8 on 2026-09-01 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteboardSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_id', models.UUIDField(db_index=True, unique=True)),
                ('crdt_state', models.BinaryField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['room_id', 'is_active'], name='whiteboard__room_id_86bfea_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhiteboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_id', models.UUIDField(db_index=True)),
                ('state_json', models.JSONField()),
                ('version', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['room_id', '-created_at'], name='whiteboard__room_id_53827b_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhiteboardStroke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_id', models.UUIDField(db_index=True)),
                ('tool', models.CharField(choices=[('pen', 'Pen'), ('highlighter', 'Highlighter'), ('eraser', 'Eraser'), ('rect', 'Rectangle'), ('circle', 'Circle'), ('line', 'Line'), ('arrow', 'Arrow'), ('text', 'Text'), ('sticky', 'Sticky Note'), ('laser', 'Laser Pointer')], max_length=20)),
                ('color', models.CharField(max_length=7)),
                ('width', models.FloatField(default=2.0)),
                ('opacity', models.FloatField(default=1.0)),
                ('points', models.JSONField()),
                ('shape_data', models.JSONField(blank=True, null=True)),
                ('is_eraser_stroke', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboard_strokes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['room_id', 'created_at'], name='whiteboard__room_id_d43d3e_idx')],
            },
        ),
    ]
