# Generated by Django 6.0.8 on 2026-08-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_key',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
