# Generated by Django 5.2.17 on 2026-09-09 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_course_duration_course_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Rich text/Markdown content')),
                ('target', models.CharField(choices=[('all', 'All Users'), ('students', 'Students Only'), ('instructors', 'Instructors Only'), ('admins', 'Admins Only'), ('course_students', 'Students in Specific Course'), ('course_instructors', 'Instructors of Specific Course'), ('enrolled_users', 'Enrolled Users (Students + Instructors)')], db_index=True, default='all', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('publish_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('push_sent', models.BooleanField(default=False)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('pin_to_top', models.BooleanField(default=False)),
                ('allow_comments', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=True)),
                ('send_push', models.BooleanField(default=True)),
                ('author', models.ForeignKey(limit_choices_to={'role__in': ['admin', 'instructor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_announcements', to=settings.AUTH_USER_MODEL)),
                ('target_courses', models.ManyToManyField(blank=True, help_text='Courses to target when target is course_students, course_instructors, or enrolled_users', related_name='targeted_announcements', to='courses.course')),
            ],
            options={
                'ordering': ('-pin_to_top', '-publish_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AnnouncementComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='announcements.announcement')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='announcements.announcementcomment')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AnnouncementReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='announcements.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-read_at',),
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', 'publish_at'], name='announcemen_status_7a06c7_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['target', 'status'], name='announcemen_target_6852b2_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['author', 'status'], name='announcemen_author__978e33_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementcomment',
            index=models.Index(fields=['announcement', '-created_at'], name='announcemen_announc_94adba_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementreadreceipt',
            index=models.Index(fields=['announcement', 'user'], name='announcemen_announc_cee019_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementreadreceipt',
            constraint=models.UniqueConstraint(fields=('announcement', 'user'), name='unique_announcement_read'),
        ),
    ]
