# Generated by Django 6.0.8 on 2026-09-01 21:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_lesson_video_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField(help_text='HTML content with placeholders')),
                ('text_content', models.TextField(blank=True, help_text='Plain text fallback')),
                ('available_variables', models.JSONField(blank=True, default=list, help_text='List of available template variables')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('custom_html', models.TextField(blank=True)),
                ('custom_text', models.TextField(blank=True)),
                ('from_name', models.CharField(default='VaceUp Team', max_length=100)),
                ('from_email', models.EmailField(default='noreply@vaceup.ng', max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('audience_filter', models.CharField(choices=[('all_users', 'All Users'), ('never_purchased', 'Never Purchased'), ('never_enrolled', 'Never Enrolled'), ('free_only', 'Free Courses Only'), ('paid_only', 'Paid Courses Only'), ('specific_courses', 'Specific Courses'), ('inactive_users', 'Inactive Users (30+ days)'), ('new_users', 'New Users (last 7 days)'), ('custom', 'Custom Query')], default='never_purchased', max_length=30)),
                ('custom_query', models.JSONField(blank=True, default=dict, help_text='Custom Django ORM filter as JSON')),
                ('exclude_purchased', models.BooleanField(default=True)),
                ('exclude_unsubscribed', models.BooleanField(default=True)),
                ('exclude_bounced', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('batch_size', models.PositiveIntegerField(default=100, help_text='Emails per batch (max 1000)')),
                ('delay_between_batches', models.PositiveIntegerField(default=5, help_text='Seconds between batches')),
                ('track_opens', models.BooleanField(default=True)),
                ('track_clicks', models.BooleanField(default=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('opened_count', models.PositiveIntegerField(default=0)),
                ('clicked_count', models.PositiveIntegerField(default=0)),
                ('bounced_count', models.PositiveIntegerField(default=0)),
                ('unsubscribed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('target_courses', models.ManyToManyField(blank=True, related_name='email_campaigns', to='courses.course')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='marketing.emailtemplate')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('unsubscribed', 'Unsubscribed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('open_token', models.CharField(blank=True, max_length=64)),
                ('click_token', models.CharField(blank=True, max_length=64)),
                ('unsubscribe_token', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='marketing.emailcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('unsubscribed', 'Unsubscribed'), ('failed', 'Failed'), ('complained', 'Complained')], max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='marketing.emailcampaign')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='marketing.emailrecipient')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('reason', models.CharField(choices=[('unsubscribed', 'Unsubscribed'), ('bounced_hard', 'Hard Bounce'), ('bounced_soft', 'Soft Bounce'), ('complained', 'Spam Complaint'), ('blocked', 'Blocked')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppressions', to='marketing.emailcampaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailUnsubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unsubscribe_all', models.BooleanField(default=False)),
                ('marketing_emails', models.BooleanField(default=True)),
                ('product_updates', models.BooleanField(default=True)),
                ('course_announcements', models.BooleanField(default=True)),
                ('promotional_offers', models.BooleanField(default=True)),
                ('weekly_digest', models.BooleanField(default=True)),
                ('unsubscribe_token', models.CharField(max_length=64, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='emailrecipient',
            index=models.Index(fields=['campaign', 'status'], name='marketing_e_campaig_e4e899_idx'),
        ),
        migrations.AddIndex(
            model_name='emailrecipient',
            index=models.Index(fields=['user', 'status'], name='marketing_e_user_id_af7255_idx'),
        ),
        migrations.AddIndex(
            model_name='emailrecipient',
            index=models.Index(fields=['email'], name='marketing_e_email_a3c536_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailrecipient',
            constraint=models.UniqueConstraint(fields=('campaign', 'user'), name='unique_campaign_recipient'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['campaign', 'event_type'], name='marketing_e_campaig_d6b3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['recipient', 'event_type'], name='marketing_e_recipie_cbccb3_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['timestamp'], name='marketing_e_timesta_7e3a12_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsuppression',
            index=models.Index(fields=['email'], name='marketing_e_email_f0f2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsuppression',
            index=models.Index(fields=['reason'], name='marketing_e_reason_18ec7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailsuppression',
            constraint=models.UniqueConstraint(fields=('email', 'reason'), name='unique_email_suppression'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['status', 'scheduled_at'], name='marketing_e_status_2603f4_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['created_by', 'status'], name='marketing_e_created_70938e_idx'),
        ),
    ]
