/** Shared by navigation and the guide so destinations cannot drift apart. */
export const ADMIN_SECTIONS = [
  { id: 'overview', name: 'Overview', icon: 'grid-1x2', group: 'Start here',
    description: 'See the academy at a glance and choose your next task.',
    steps: ['Review student, course and enrollment totals.', 'Use the quick actions to open the area that needs attention.'],
    hint: 'Start here each day, then check Applications for pending decisions.' },
  { id: 'users', name: 'Users', icon: 'people', group: 'People & access',
    description: 'Find learners and manage tutor or administrator accounts.',
    steps: ['Search the user directory by name or email and filter by role.', 'Create a tutor or administrator account when staff need access.', 'Review the correct account before changing its role or active status.'],
    hint: 'Give administrator access only to people who manage the academy. Tutors use the instructor role.' },
  { id: 'courses', name: 'Courses', icon: 'book', group: 'Course setup',
    description: 'Create courses and control what appears in the public catalog.',
    steps: ['Define or rename Categories, then create a course with its category, tutor, level, description and price.', 'Keep it in draft while you prepare lessons in Content.', 'Review its details, then publish it. The homepage and public catalogue read published courses from this backend.'],
    hint: 'Set up categories and an active tutor first. Only published courses appear to visitors; import the previous homepage courses as drafts using the deployment guide.' },
  { id: 'content', name: 'Content', icon: 'folder-open', group: 'Course setup',
    description: 'Organize each course into modules and lessons.',
    steps: ['Select the course you want to work on.', 'Add modules, then add lessons and their video links.', 'Check the lesson titles, order and links before publishing the course.'],
    hint: 'A course needs to exist before you can add its content.' },
  { id: 'liveclasses', name: 'Live Classes', icon: 'camera-video', group: 'Teaching',
    description: 'Schedule the sessions learners will attend.',
    steps: ['Choose the course and enter the session title.', 'Set the start time, duration and meeting details.', 'Review the scheduled sessions and confirm the time with your tutor.'],
    hint: 'Confirm the displayed date and time before sharing the class with learners.' },
  { id: 'assignments', name: 'Assignments', icon: 'file-earmark-text', group: 'Teaching',
    description: 'Create assessments and review learner submissions.',
    steps: ['Use New Assignment or New Quiz in this section.', 'Choose the course, add instructions and set the deadline or pass requirements.', 'Review submissions and record grades with useful feedback.'],
    hint: 'The current quiz form creates the quiz; questions need to be added through the available question builder or Django admin.' },
  { id: 'certificates', name: 'Certificates', icon: 'award', group: 'Teaching',
    description: 'Review awards and issue certificates to eligible learners.',
    steps: ['Select the student and course and check their completion record.', 'Review the certificate preview, then issue it.', 'Use the certificate list to inspect existing awards or revoke an incorrect one.'],
    hint: 'Confirm the learner name and course before issuing. Revoking changes the validity of an existing award.' },
  { id: 'enrollments', name: 'Enrollments', icon: 'person-check', group: 'People & access',
    description: 'Review which learners have access to each course.',
    steps: ['Search the enrollment list to find the learner and course.', 'Review their status and recorded progress.', 'If access needs changing, use the enrollment controls in Django admin or ask your technical team.'],
    hint: 'Payment records and enrollment access are separate. Check both when resolving an access query.' },
  { id: 'payments', name: 'Payments', icon: 'cash-coin', group: 'Operations',
    description: 'Review payment records when reconciling fees or helping a learner.',
    steps: ['Find the learner payment and check its reference, amount and status.', 'Compare the record with Paystack when investigating a payment query.', 'Check Enrollments to confirm the learner has the correct course access.'],
    hint: 'A payment screenshot is not confirmation. Verify the provider record before granting paid access.' },
  { id: 'applications', name: 'Applications', icon: 'file-earmark-text', group: 'People & access',
    description: 'Review course applications and record admissions decisions.',
    steps: ['Review each pending application and the course requested.', 'Check the applicant details before approving or rejecting.', 'Confirm the resulting status and follow up on any access questions.'],
    hint: 'Use a consistent admissions process; approval and payment are different decisions.' },
  { id: 'announcements', name: 'Announcements', icon: 'megaphone', group: 'Communications',
    description: 'Prepare and publish academy updates.',
    steps: ['Write a clear title and message.', 'Review the content and intended audience before publishing.', 'Check the published and draft list to avoid duplicate updates.'],
    hint: 'Include the action learners need to take and any relevant deadline.' },
  { id: 'flags', name: 'Feature Flags', icon: 'toggles', group: 'Operations',
    description: 'Manage the platform settings exposed in the control panel.',
    steps: ['Read the setting name and current value.', 'Confirm the intended effect before editing.', 'Save the specific setting and check the affected feature.'],
    hint: 'Coordinate unfamiliar settings with your technical team before changing them.' },
  { id: 'marketing', name: 'Marketing', icon: 'send', group: 'Communications',
    description: 'Review campaigns and manage their available actions.',
    steps: ['Inspect the campaign list and its current status.', 'Check the audience and message before using a send or schedule action.', 'Review the outcome before repeating an action.'],
    hint: 'Sending a campaign reaches real recipients. Confirm its audience and content first.' },
] as const;

export type AdminTab = typeof ADMIN_SECTIONS[number]['id'];
export const adminHref = (tab: AdminTab) => tab === 'overview' ? '/dashboard' : `/dashboard?tab=${tab}`;
export function resolveAdminTab(value: string | null | undefined): AdminTab {
  return ADMIN_SECTIONS.find((section) => section.id === value)?.id ?? 'overview';
}
