# Generated by Django 5.2.17 on 2026-09-08 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_lesson_video_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_deactivate', 'User Deactivated'), ('user_activate', 'User Activated'), ('user_promote', 'User Promoted'), ('user_demote', 'User Demoted'), ('course_create', 'Course Created'), ('course_update', 'Course Updated'), ('course_publish', 'Course Published'), ('course_unpublish', 'Course Unpublished'), ('course_delete', 'Course Deleted'), ('course_bulk_price', 'Bulk Price Update'), ('tutor_invite', 'Tutor Invited'), ('tutor_create', 'Tutor Created'), ('tutor_update', 'Tutor Updated'), ('staff_deactivate', 'Staff Deactivated'), ('staff_activate', 'Staff Activated'), ('staff_promote', 'Staff Promoted'), ('application_review', 'Application Reviewed'), ('announcement_create', 'Announcement Created'), ('settings_update', 'Settings Updated')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('admin', models.ForeignKey(limit_choices_to={'role__in': ['admin', 'instructor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to='courses.course')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_on_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['admin', '-created_at'], name='adminpanel__admin_i_be6acc_idx'), models.Index(fields=['action_type', '-created_at'], name='adminpanel__action__bb2938_idx'), models.Index(fields=['target_user', '-created_at'], name='adminpanel__target__3553bf_idx'), models.Index(fields=['target_course', '-created_at'], name='adminpanel__target__c2f1f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('target', models.CharField(choices=[('all', 'All Users'), ('students', 'Students Only'), ('instructors', 'Instructors Only'), ('admins', 'Admins Only')], default='all', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['is_published', 'publish_at'], name='adminpanel__is_publ_a40523_idx'), models.Index(fields=['target', 'is_published'], name='adminpanel__target_0d98dc_idx')],
            },
        ),
    ]
