# Generated by Django 5.2.17 on 2026-09-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactionlog',
            name='action_type',
            field=models.CharField(choices=[('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_deactivate', 'User Deactivated'), ('user_activate', 'User Activated'), ('user_promote', 'User Promoted'), ('user_demote', 'User Demoted'), ('user_delete', 'User Permanently Deleted'), ('course_create', 'Course Created'), ('course_update', 'Course Updated'), ('course_publish', 'Course Published'), ('course_unpublish', 'Course Unpublished'), ('course_delete', 'Course Deleted'), ('course_bulk_price', 'Bulk Price Update'), ('tutor_invite', 'Tutor Invited'), ('tutor_create', 'Tutor Created'), ('tutor_update', 'Tutor Updated'), ('staff_deactivate', 'Staff Deactivated'), ('staff_activate', 'Staff Activated'), ('staff_promote', 'Staff Promoted'), ('application_review', 'Application Reviewed'), ('announcement_create', 'Announcement Created'), ('settings_update', 'Settings Updated')], db_index=True, max_length=30),
        ),
    ]
